### ISSUE TITLE
Crash in Gm mode

### ISSUE THREAD

**Issue by BenoitMorel** [AADavin/Zombi#10]
Hello everyone,

thank you so much for developing Zombi :-)

I recently switched to the Gm mode to use per-family rates. I had a crash because Zombi couldn't find the file `ScaledEvents.tsv`

I found a bypass, but I don't know if that's correct: I edited the line https://github.com/AADavin/Zombi/blob/master/Zombi.py#L137
and replaced the filename with `REDScaledEvents.tsv`

Let me know if you need the configuration files to reproduce.
Best,
Benoit

**Comment by theotricou** [comment]
Hello Benoit,
Thank you for the feed back. I made the change in the script, but I could not reproduce the error before. Could you send me your configuration files and the command lines.

Thank you
Théo

**Comment by BenoitMorel** [comment]
Salut Théo,

Thanks a lot!
I am running:
```
python Zombi.py T SpeciesTreeParameters.tsv .
python Zombi.py Gm GenomeTreeParameters.tsv .
```

and get the following error message 

```
Writing Genomes
Writing Family rates
Writing Gene Families
Writing Profiles
Writing Events Per Branch
Traceback (most recent call last):
  File "../../../ZOMBI/Zombi.py", line 436, in <module>
    Z.G(parameters_file, experiment_folder, advanced_mode)
  File "../../../ZOMBI/Zombi.py", line 199, in G
    gss.write_events_per_branch(events_per_branch_folder, scale, scaled_file, events_file)
  File "/data/morelbt/github/ZOMBI/GenomeSimulator.py", line 205, in write_events_per_branch
    with open(scaled_file) as f:
FileNotFoundError: [Errno 2] No such file or directory: './T/ScaledEvents.tsv'
```




Maybe you need to turn on `EVENTS_PER_BRANCH` to reproduce?

Here are the configuration files (I had to add the `.txt` extension to have them accepted by github):
[SpeciesTreeParameters.tsv.txt](https://github.com/AADavin/Zombi/files/9951236/SpeciesTreeParameters.tsv.txt)
[GenomeTreeParameters.tsv.txt](https://github.com/AADavin/Zombi/files/9951235/GenomeTreeParameters.tsv.txt)

Cheers,
Benoit
