### ISSUE TITLE
Molecular Clock Tutorial Error

### ISSUE THREAD

**Issue by MartGro** [AADavin/Zombi#8]
Hi,
I was trying to get the Tutorial No1 to run, but it exits with an error:
`python3 Zombi.py T ./Tutorials/Tutorial1/SpeciesTreeParameters.tsv MC_test`

returns the following error:

...
Time: 99.85704549536541 ; Number of lineages alive: 174
Time: 99.93861005352342 ; Number of lineages alive: 175
Time: 99.95671755007255 ; Number of lineages alive: 174
Traceback (most recent call last):
  File "Zombi.py", line 427, in <module>
    Z.T(parameters_file, experiment_folder, advanced_mode)
  File "Zombi.py", line 112, in T
    if parameters["SCALE_TREE"] != 0:
KeyError: 'SCALE_TREE'

**Comment by theotricou** [comment]
Hi MartGo,

The SpeciesTree Parameters file was not updated.
It should work know.
Just clone the current version of Zombi repo.

Theo

**Comment by MartGro** [comment]
Thanks for the quick reply, it works now.

When running `python RateCustomizer.py S SequenceParameters.tsv MC_test`, I got another error:

Traceback (most recent call last):
  File "RateCustomizer.py", line 204, in <module>
    parameters = af.prepare_genome_parameters(af.read_parameters(parameters_file))
  File "home/user_ab/ZOMBI/AuxiliarFunctions.py", line 55, in read_parameters
    with open(parameters_file) as f:
FileNotFoundError: [Errno 2] No such file or directory: 'SequenceParameters.tsv'


I could solve it by using:
`python RateCustomizer.py S "Tutorials/Tutorial1/SequenceParameters.tsv" MC_test` 

Where is the SequenceParameters.tsv file supposed to be?

**Comment by MartGro** [comment]
Perfect, thanks a lot :+1: 
Maybe it would be good to also describe that in the Wiki of the Tutorial.
Best,
Martin
