### ISSUE TITLE
using input tree with Ti model 

### ISSUE THREAD

**Issue by dfeistel3** [AADavin/Zombi#9]
I'm using the Ti model to generate a species tree using a tree from real genomes.  I keep getting this error:

Traceback (most recent call last):
  File "Zombi.py", line 427, in <module>
    Z.T(parameters_file, experiment_folder, advanced_mode)
  File "Zombi.py", line 33, in T
    stg.events = af.generate_events(tree_file)
  File "/storage/coda1/p-ktk3/0/dfeistel3/rich_project_bio-konstantinidis/apps/ZOMBI/AuxiliarFunctions.py", line 314, in generate_events
    c1, c2 = node.get_children()
ValueError: too many values to unpack (expected 2)

any advice?

**Comment by theotricou** [comment]
Hello dfeistel3,

This error could arise from a non binary tree. Zombi do not take trees with multifurcations as input.
It could be that your newick tree is not strictly a in a newick format.
Or it is not a rooted tree, ...

Could you show me the tree you are using as input ?

Cheers
Theo

**Comment by dfeistel3** [comment]
What do yo mean by show you.  Picture of the tree or the input file?

**Comment by theotricou** [comment]
Sharing the newick file that you used as input.

**Comment by theotricou** [comment]
I am closing this issue, as there is no more contact !
